---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 👇 Add this temporary debug step before Docker login
      - name: Debug secrets (remove after testing)
        run: |
          echo "Username is set: ${{ secrets.DOCKERHUB_USER != '' }}"
          echo "Token is set: ${{ secrets.DOCKERHUB_TOKEN != '' }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Lint Code
        run: docker compose run --rm app sh -c "flake8"
